# Author: crifan
# Date: 2012-05-16
#
# -----------------------------------------------------------------
#  generate output from DocBook sources
#  this is entry makefile for docbook
# -----------------------------------------------------------------
# run this makefile under src directory:
# [office]
# pwd = /home/CLi/develop/docbook/books/xxx/src
# [home]
# pwd = /cygdrive/e/Dev_Root/docbook/dev/books/xxx/src

################################################################################
# Project Settings
################################################################################

# also means main source file name
PROJECT_NAME = mpeg_vbr
SUB_SRC_FILES = \
    preface.xml \
    ch01_mpeg_related.xml \
    ch02_mp3_term.xml \
    ch03_mpeg_frame.xml \
    ch04_xing_vbri.xml \
    ch05_calc_duration.xml \
    ch06_mp3_related.xml \
    ch07_after_content.xml \
    reference.xml

DOCBOOK_MAKEFILE_ROOT = ../../../config
################################################################################
# Include docbook makefile
################################################################################
include $(DOCBOOK_MAKEFILE_ROOT)/docbook.mk